services:
  - type: web
    name: mp3-backend
    env: node
    buildCommand: |
      npm install
      pip install yt-dlp
      apt-get update && apt-get install -y ffmpeg
    startCommand: node server.js